theme: jekyll-theme-minimal
title: Max J Espinoza
description: My Personal Page
logo: https://raw.githubusercontent.com/espinm2/espinm2.github.io/refs/heads/main/assets/max-profile.png
show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]
